### ISSUE TITLE
Disable/enable cortile based on monitor setup?

### ISSUE THREAD

**Issue by alexzeitgeist** [leukipp/cortile-addons#2]
Would it be possible to use the bindings to dynamically enable or disable Cortile based on the current monitor setup?

For example, if my laptop is docked to a multi-monitor setup, I want cortile to be enabled. But if I undock the laptop, I would like via script to 

- maximize all previously tiled windows
- disable cortile

Furthermore, in a multi-monitor setup, I would like to define whether to enable or disable tiling for a specific monitor.

Cheers
Alex

**Comment by leukipp** [comment]
If you just run `cortile` without caching disabled (`- cache 0`), you will get most of your requirements for free, because cortile will remember tiling states, layouts etc. per work**place** (physical connected screens) as described here:
https://github.com/leukipp/cortile/issues/44

With that said, it would be possible to do this via Python bindings by simply listening for “Workplace” changes and then applying some layouts based on the new screen count/dimensions. 
If you need to run it via `cortile - cache 0` let me know why, because tackling this may be less work.

**Comment by alexzeitgeist** [comment]
@leukipp apologies, should have responded a long time ago. Everything is good, you're right, it works well out of the box. Don't know why, but I had caching disabled a long time ago, probably due to a bug on my side. Everything is working fine now.
